<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["ipv4", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create ipv4
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "ipv4/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIpFrom" class="col-sm-2 control-label">Ip Of From</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["ip_from", "size" => 30, "class" => "form-control", "id" => "fieldIpFrom"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIpTo" class="col-sm-2 control-label">Ip Of To</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["ip_to", "size" => 30, "class" => "form-control", "id" => "fieldIpTo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCountryCode" class="col-sm-2 control-label">Country Of Code</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["country_code", [], "class" => "form-control", "id" => "fieldCountryCode"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCountryName" class="col-sm-2 control-label">Country Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["country_name", "size" => 30, "class" => "form-control", "id" => "fieldCountryName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRegionName" class="col-sm-2 control-label">Region Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["region_name", "size" => 30, "class" => "form-control", "id" => "fieldRegionName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCityName" class="col-sm-2 control-label">City Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["city_name", "size" => 30, "class" => "form-control", "id" => "fieldCityName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLatitude" class="col-sm-2 control-label">Latitude</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["latitude", "size" => 30, "class" => "form-control", "id" => "fieldLatitude"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLongitude" class="col-sm-2 control-label">Longitude</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["longitude", "size" => 30, "class" => "form-control", "id" => "fieldLongitude"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldZipCode" class="col-sm-2 control-label">Zip Of Code</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["zip_code", "size" => 30, "class" => "form-control", "id" => "fieldZipCode"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTimeZone" class="col-sm-2 control-label">Time Of Zone</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["time_zone", "size" => 30, "class" => "form-control", "id" => "fieldTimeZone"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
